import type { ReactElement } from "react";
import {
  ButtonGroupDoc,
  CheckboxDoc,
  InputDoc,
  RadioDoc,
  SelectDoc,
  SliderDoc,
  SwitchDoc,
  TextareaDoc,
} from "./components/FormDocs";
import {
  AlertDoc,
  AvatarDoc,
  BadgeDoc,
  CardDoc,
  ChipDoc,
  KbdDoc,
  ProgressDoc,
  SkeletonDoc,
  SnippetDoc,
  SpinnerDoc,
  TableDoc,
} from "./components/DisplayDocs";
import {
  AccordionDoc,
  BreadcrumbsDoc,
  DrawerDoc,
  MenuDoc,
  ModalDoc,
  PaginationDoc,
  TabsDoc,
  ToastDoc,
  TooltipDoc,
} from "./components/NavDocs";
import {
  AccessibilityPage,
  ColorPage,
  ElevationPage,
  MotionPage,
  SpacingPage,
  TokensPage,
  TypographyPage,
} from "./Foundations";
import { ThemePage } from "./Theme";
import { BlocksPage } from "./Blocks";
import { ComponentsIndex } from "./ComponentsIndex";
import {
  CommerceDoc,
  DataTableDoc,
  FileUploadDoc,
  OverflowDoc,
  SystemUIDoc,
} from "./components/ProDocs";
import { IconsPage as RemixIconsPage } from "./Icons";
import {
  AlertDialogDoc,
  BadgeSpecDoc,
  ButtonSpecDoc,
  ButtonTileDoc,
  ChatInputDoc,
  ComboboxDoc,
  HoverCardDoc,
  InfoLabelDoc,
  ListItemDoc,
  PaymentCardDoc,
  ToolbarDoc,
  WellDoc,
} from "./components/PatternDocs";
import {
  ColorPickerDoc,
  ContentDividerDoc,
  DropdownDoc,
  EmptyStateDoc,
  InputsMoreDoc,
  RatingDoc,
  SelectionCardDoc,
  TimelineDoc,
  ToggleGroupDoc,
  VerticalTabDoc,
  WidgetBoxDoc,
} from "./components/MoreDocs";
import {
  BannerDoc,
  CompactButtonDoc,
  DatepickerDoc,
  DigitInputDoc,
  FancyButtonDoc,
  FileIconDoc,
  LabelHintDoc,
  LinkButtonDoc,
  NotificationDoc,
  SegmentedDoc,
  SocialButtonDoc,
  StatusBadgeDoc,
  StepperDoc,
  TagDoc,
} from "./components/ExtraDocs";
import { ChangelogPage, InstallationPage, IntroductionPage, PrinciplesPage } from "./GettingStarted";
import { PricingPage, RoadmapPage, TemplatesPage } from "./Marketing";

export const ROUTES: Record<string, (nav: (t: string) => void) => ReactElement> = {
  "docs/introduction": (nav) => <IntroductionPage navigate={nav} />,
  "docs/installation": (nav) => <InstallationPage navigate={nav} />,
  "docs/principles": () => <PrinciplesPage />,
  "docs/changelog": () => <ChangelogPage />,

  "foundations/color": () => <ColorPage />,
  "foundations/typography": () => <TypographyPage />,
  "foundations/spacing": () => <SpacingPage />,
  "foundations/elevation": () => <ElevationPage />,
  "foundations/motion": () => <MotionPage />,
  "foundations/icons": () => <RemixIconsPage />,
  "foundations/accessibility": () => <AccessibilityPage />,
  "foundations/tokens": () => <TokensPage />,

  theme: () => <ThemePage />,
  pricing: (nav) => <PricingPage navigate={nav} />,
  templates: (nav) => <TemplatesPage navigate={nav} />,
  "docs/roadmap": () => <RoadmapPage />,
  blocks: () => <BlocksPage />,
  components: (nav) => <ComponentsIndex navigate={nav} />,

  "components/data-table": (nav) => <DataTableDoc navigate={nav} />,
  "components/file-upload": (nav) => <FileUploadDoc navigate={nav} />,
  "components/overflow-utilities": (nav) => <OverflowDoc navigate={nav} />,
  "components/commerce": (nav) => <CommerceDoc navigate={nav} />,
  "components/system-ui": (nav) => <SystemUIDoc navigate={nav} />,

  "components/toggle-group": () => <ToggleGroupDoc />,
  "components/button-tile": () => <ButtonTileDoc />,
  "components/toolbar": () => <ToolbarDoc />,
  "components/combobox": () => <ComboboxDoc />,
  "components/chat-input": () => <ChatInputDoc />,
  "components/info-label": () => <InfoLabelDoc />,
  "components/list-item": () => <ListItemDoc />,
  "components/payment-card": () => <PaymentCardDoc />,
  "components/well": () => <WellDoc />,
  "components/alert-dialog": () => <AlertDialogDoc />,
  "components/hover-card": () => <HoverCardDoc />,
  "components/selection-card": () => <SelectionCardDoc />,
  "components/inputs-more": () => <InputsMoreDoc />,
  "components/rating": () => <RatingDoc />,
  "components/color-picker": () => <ColorPickerDoc />,
  "components/widget-box": () => <WidgetBoxDoc />,
  "components/content-divider": () => <ContentDividerDoc />,
  "components/timeline": () => <TimelineDoc />,
  "components/tab-menu-vertical": () => <VerticalTabDoc />,
  "components/dropdown": () => <DropdownDoc />,
  "components/empty-state": () => <EmptyStateDoc />,
  "components/pricing-card": (nav) => <CommerceDoc navigate={nav} />,
  "components/order-summary": (nav) => <CommerceDoc navigate={nav} />,
  "components/team-member-card": (nav) => <CommerceDoc navigate={nav} />,
  "components/stat-card": (nav) => <CommerceDoc navigate={nav} />,
  "components/chat-bubble": (nav) => <CommerceDoc navigate={nav} />,
  "components/carousel": (nav) => <OverflowDoc navigate={nav} />,
  "components/tree-view": (nav) => <OverflowDoc navigate={nav} />,
  "components/metre": (nav) => <SystemUIDoc navigate={nav} />,
  "components/scroll-area": (nav) => <SystemUIDoc navigate={nav} />,
  "components/error-page": (nav) => <SystemUIDoc navigate={nav} />,
  "components/cookie-consent": (nav) => <SystemUIDoc navigate={nav} />,

  "components/fancy-button": () => <FancyButtonDoc />,
  "components/compact-button": () => <CompactButtonDoc />,
  "components/link-button": () => <LinkButtonDoc />,
  "components/social-button": () => <SocialButtonDoc />,
  "components/digit-input": () => <DigitInputDoc />,
  "components/datepicker": () => <DatepickerDoc />,
  "components/label-hint": () => <LabelHintDoc />,
  "components/status-badge": () => <StatusBadgeDoc />,
  "components/tag": () => <TagDoc />,
  "components/file-format-icon": () => <FileIconDoc />,
  "components/segmented-control": () => <SegmentedDoc />,
  "components/stepper": () => <StepperDoc />,
  "components/notification": () => <NotificationDoc />,
  "components/banner": () => <BannerDoc />,

  "components/button": () => <ButtonSpecDoc />,
  "components/button-group": () => <ButtonGroupDoc />,
  "components/input": () => <InputDoc />,
  "components/textarea": () => <TextareaDoc />,
  "components/select": () => <SelectDoc />,
  "components/checkbox": () => <CheckboxDoc />,
  "components/radio-group": () => <RadioDoc />,
  "components/switch": () => <SwitchDoc />,
  "components/slider": () => <SliderDoc />,

  "components/card": () => <CardDoc />,
  "components/table": () => <TableDoc />,
  "components/avatar": () => <AvatarDoc />,
  "components/chip": () => <ChipDoc />,
  "components/badge-spec": () => <BadgeSpecDoc />,
  "components/badge": () => <BadgeSpecDoc />,
  "components/badge-overlay": () => <BadgeDoc />,
  "components/progress": () => <ProgressDoc />,
  "components/skeleton": () => <SkeletonDoc />,
  "components/snippet": () => <SnippetDoc />,
  "components/kbd": () => <KbdDoc />,

  "components/tabs": () => <TabsDoc />,
  "components/accordion": () => <AccordionDoc />,
  "components/breadcrumbs": () => <BreadcrumbsDoc />,
  "components/pagination": () => <PaginationDoc />,

  "components/alert": () => <AlertDoc />,
  "components/toast": () => <ToastDoc />,
  "components/modal": () => <ModalDoc />,
  "components/drawer": () => <DrawerDoc />,
  "components/tooltip": () => <TooltipDoc />,
  "components/menu": () => <MenuDoc />,
  "components/spinner": () => <SpinnerDoc />,
};
