// Auto-generated curated Remix Icon catalogue
import {
  RiArrowDownSLine,
  RiArrowUpSLine,
  RiArrowRightSLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiArrowRightUpLine,
  RiArrowLeftDownLine,
  RiAddLine,
  RiSubtractLine,
  RiSearchLine,
  RiSearch2Line,
  RiCloseLine,
  RiCheckLine,
  RiStarFill,
  RiStarLine,
  RiStarHalfFill,
  RiUserLine,
  RiUser3Line,
  RiSettings3Line,
  RiSettings2Line,
  RiLogoutBoxRLine,
  RiInboxLine,
  RiFileTextLine,
  RiErrorWarningFill,
  RiInformationFill,
  RiAlertFill,
  RiMoreLine,
  RiMore2Line,
  RiBold,
  RiItalic,
  RiUnderline,
  RiAlignLeft,
  RiAlignCenter,
  RiAlignRight,
  RiAlignJustify,
  RiPaletteLine,
  RiEyeLine,
  RiEyeOffLine,
  RiTeamLine,
  RiRocketLine,
  RiRocket2Line,
  RiBuildingLine,
  RiBuilding2Line,
  RiGlobalLine,
  RiTimeLine,
  RiGitCommitLine,
  RiGitBranchLine,
  RiGitPullRequestLine,
  RiGitMergeLine,
  RiShieldCheckLine,
  RiShieldLine,
  RiFlashlightLine,
  RiHome5Line,
  RiHome4Line,
  RiDashboardLine,
  RiDashboard3Line,
  RiNotification3Line,
  RiNotificationLine,
  RiMailLine,
  RiMailOpenLine,
  RiMailSendLine,
  RiCalendarLine,
  RiCalendar2Line,
  RiCalendarEventLine,
  RiFolderLine,
  RiFolder3Line,
  RiFolderOpenLine,
  RiImageLine,
  RiImage2Line,
  RiLockLine,
  RiLock2Line,
  RiLockUnlockLine,
  RiHeartLine,
  RiHeart3Line,
  RiBookmarkLine,
  RiDownloadLine,
  RiDownload2Line,
  RiUploadLine,
  RiUpload2Line,
  RiShareLine,
  RiShareForwardLine,
  RiDeleteBinLine,
  RiDeleteBin6Line,
  RiEditLine,
  RiEdit2Line,
  RiPencilLine,
  RiFilterLine,
  RiFilter3Line,
  RiSortDesc,
  RiSortAsc,
  RiRefreshLine,
  RiLoopLeftLine,
  RiExternalLinkLine,
  RiLinkM,
  RiLink,
  RiLinkUnlinkM,
  RiCodeLine,
  RiCodeSSlashLine,
  RiTerminalBoxLine,
  RiTerminalLine,
  RiCloudLine,
  RiCloudOffLine,
  RiDatabase2Line,
  RiServerLine,
  RiCpuLine,
  RiSmartphoneLine,
  RiComputerLine,
  RiMacbookLine,
  RiTabletLine,
  RiMoonLine,
  RiSunLine,
  RiMapPinLine,
  RiMapPin2Line,
  RiPhoneLine,
  RiChat1Line,
  RiChat3Line,
  RiMessage2Line,
  RiMessage3Line,
  RiQuestionLine,
  RiQuestionnaireLine,
  RiAlarmLine,
  RiTimerLine,
  RiHistoryLine,
  RiBarChartLine,
  RiBarChart2Line,
  RiBarChartBoxLine,
  RiLineChartLine,
  RiPieChartLine,
  RiPieChart2Line,
  RiWalletLine,
  RiWallet3Line,
  RiCoinLine,
  RiCoinsLine,
  RiShoppingBagLine,
  RiStore2Line,
  RiGiftLine,
  RiTicketLine,
  RiCouponLine,
  RiTrophyLine,
  RiMedalLine,
  RiAwardLine,
  RiVipCrownLine,
  RiMagicLine,
  RiSparklingLine,
  RiSparkling2Line,
  RiLayoutLine,
  RiLayout4Line,
  RiLayoutGridLine,
  RiGridLine,
  RiListCheck,
  RiListCheck2,
  RiMenuLine,
  RiMenu2Line,
  RiSideBarLine,
  RiFullscreenLine,
  RiZoomInLine,
  RiZoomOutLine,
  RiPrinterLine,
  RiSave3Line,
  RiClipboardLine,
  RiFileCopyLine,
  RiFileCopy2Line,
  RiAttachmentLine,
  RiAttachment2,
  RiMicLine,
  RiMicOffLine,
  RiVideoLine,
  RiVideoAddLine,
  RiCameraLine,
  RiMusic2Line,
  RiPlayLine,
  RiPauseLine,
  RiStopLine,
  RiSkipForwardLine,
  RiSkipBackLine,
  RiVolumeUpLine,
  RiVolumeMuteLine,
  RiFlagLine,
  RiFlag2Line,
  RiPushpinLine,
  RiPushpin2Line,
  RiKeyLine,
  RiKey2Line,
  RiFingerprintLine,
  RiUserAddLine,
  RiUserFollowLine,
  RiGroupLine,
  RiGroup2Line,
  RiUserStarLine,
  RiUserSettingsLine,
  RiBriefcaseLine,
  RiBriefcase4Line,
  RiSuitcaseLine,
  RiSunCloudyLine,
  RiRainyLine,
  RiFireLine,
  RiDropLine,
  RiCompassLine,
  RiTranslate2,
  RiFontSize,
  RiText,
  RiH1,
  RiH2,
  RiListOrdered,
  RiListUnordered,
  RiDoubleQuotesL,
  RiTableLine,
  RiFunctionLine,
  RiBracesLine,
  RiGithubLine,
  RiGithubFill,
  RiTwitterXLine,
  RiGoogleLine,
  RiGoogleFill,
  RiAppleLine,
  RiAppleFill,
  RiFigmaLine,
  RiSlackLine,
  RiNotionLine,
  RiLinkedinBoxLine,
  RiMicrosoftLine,
  RiReactjsLine,
  RiTailwindCssLine,
  RiNextjsLine,
  RiBox3Line,
  RiArchiveLine,
  RiArchiveDrawerLine,
  RiStackLine,
  RiApps2Line,
  RiAppsLine,
  RiToolsLine,
  RiBugLine,
  RiEqualizerLine,
  RiEqualizer3Line,
  RiToggleLine,
  RiCheckboxLine,
  RiCheckboxBlankLine,
  RiRadioButtonLine,
  RiCheckboxMultipleLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiExpandUpDownLine,
  RiContractUpDownLine,
  RiHandCoinLine,
  RiThumbUpLine,
  RiThumbDownLine,
  RiEmotionLine,
  RiEmotionHappyLine,
  RiEmotionSadLine,
  RiUserSmileLine,
  RiCustomerService2Line,
  RiBookOpenLine,
  RiBook2Line,
  RiBookletLine,
  RiNewspaperLine,
  RiArticleLine,
  RiDraftLine,
  RiStickyNoteLine,
  RiTodoLine,
  RiTaskLine,
  RiCalendarCheckLine,
  RiCalendarTodoLine,
  RiLightbulbLine,
  RiLightbulbFlashLine,
  RiFlashlightFill,
  RiSunFill,
  RiMoonFill,
  RiCloudFill,
  RiHome5Fill,
  RiUser3Fill,
  RiSettings3Fill,
  RiNotification3Fill,
  RiMailFill,
  RiHeart3Fill,
  RiBookmarkFill,
  RiErrorWarningLine,
  RiInformationLine,
  RiSpam2Line,
  RiShieldKeyholeLine,
  RiVerifiedBadgeLine,
  RiVerifiedBadgeFill,
  RiLoader4Line,
  RiReplyLine,
  RiFileLine,
  RiFile3Line,
  RiFileAddLine,
  RiFileDownloadLine,
  RiFileUploadLine,
  RiFilePdfLine,
  RiFileExcelLine,
  RiFileWordLine,
  RiFilePptLine,
  RiFileZipLine,
  RiFileMusicLine,
  RiFileVideoLine,
  RiFileImageLine,
  RiFileCodeLine,
  RiFolderAddLine,
  RiFolderUploadLine,
  RiFolderDownloadLine,
  RiHardDriveLine,
  RiHardDrive2Line,
  RiPlayListLine,
  RiRepeatLine,
  RiShuffleLine,
  RiContrastLine,
  RiShapeLine,
  RiSubtractFill,
  RiAddFill,
  RiCloseFill,
  RiCheckFill,
  RiCheckDoubleLine,
  RiThumbUpFill,
  RiHeartFill,
  RiStarSFill,
  RiStarSLine,
  RiBookmark3Line,
  RiFlag2Fill,
  RiPriceTag3Line,
  RiSwapLine,
  RiArrowLeftRightLine,
  RiArrowUpDownLine,
  RiFilterOffLine,
  RiSearchEyeLine,
  RiZoomInFill,
  RiUserSearchLine,
  RiRocketFill,
  RiFirstAidKitLine,
  RiHeartAddLine,
  RiDislikeLine,
  RiZoomOutFill,
  RiDraftFill,
} from "@remixicon/react";

export const ICONS = [
  { name: "RiArrowDownSLine", Icon: RiArrowDownSLine, category: "System" },
  { name: "RiArrowUpSLine", Icon: RiArrowUpSLine, category: "System" },
  { name: "RiArrowRightSLine", Icon: RiArrowRightSLine, category: "System" },
  { name: "RiArrowLeftSLine", Icon: RiArrowLeftSLine, category: "System" },
  { name: "RiArrowRightLine", Icon: RiArrowRightLine, category: "System" },
  { name: "RiArrowLeftLine", Icon: RiArrowLeftLine, category: "System" },
  { name: "RiArrowRightUpLine", Icon: RiArrowRightUpLine, category: "System" },
  { name: "RiArrowLeftDownLine", Icon: RiArrowLeftDownLine, category: "System" },
  { name: "RiAddLine", Icon: RiAddLine, category: "System" },
  { name: "RiSubtractLine", Icon: RiSubtractLine, category: "System" },
  { name: "RiSearchLine", Icon: RiSearchLine, category: "General" },
  { name: "RiSearch2Line", Icon: RiSearch2Line, category: "Editor & Design" },
  { name: "RiCloseLine", Icon: RiCloseLine, category: "System" },
  { name: "RiCheckLine", Icon: RiCheckLine, category: "System" },
  { name: "RiStarFill", Icon: RiStarFill, category: "General" },
  { name: "RiStarLine", Icon: RiStarLine, category: "General" },
  { name: "RiStarHalfFill", Icon: RiStarHalfFill, category: "General" },
  { name: "RiUserLine", Icon: RiUserLine, category: "People" },
  { name: "RiUser3Line", Icon: RiUser3Line, category: "People" },
  { name: "RiSettings3Line", Icon: RiSettings3Line, category: "Devices & Tools" },
  { name: "RiSettings2Line", Icon: RiSettings2Line, category: "Devices & Tools" },
  { name: "RiLogoutBoxRLine", Icon: RiLogoutBoxRLine, category: "Devices & Tools" },
  { name: "RiInboxLine", Icon: RiInboxLine, category: "Communication & Media" },
  { name: "RiFileTextLine", Icon: RiFileTextLine, category: "Documents" },
  { name: "RiErrorWarningFill", Icon: RiErrorWarningFill, category: "Security & Status" },
  { name: "RiInformationFill", Icon: RiInformationFill, category: "System" },
  { name: "RiAlertFill", Icon: RiAlertFill, category: "Security & Status" },
  { name: "RiMoreLine", Icon: RiMoreLine, category: "System" },
  { name: "RiMore2Line", Icon: RiMore2Line, category: "System" },
  { name: "RiBold", Icon: RiBold, category: "Editor & Design" },
  { name: "RiItalic", Icon: RiItalic, category: "Editor & Design" },
  { name: "RiUnderline", Icon: RiUnderline, category: "Editor & Design" },
  { name: "RiAlignLeft", Icon: RiAlignLeft, category: "Editor & Design" },
  { name: "RiAlignCenter", Icon: RiAlignCenter, category: "Editor & Design" },
  { name: "RiAlignRight", Icon: RiAlignRight, category: "Editor & Design" },
  { name: "RiAlignJustify", Icon: RiAlignJustify, category: "Editor & Design" },
  { name: "RiPaletteLine", Icon: RiPaletteLine, category: "Editor & Design" },
  { name: "RiEyeLine", Icon: RiEyeLine, category: "Security & Status" },
  { name: "RiEyeOffLine", Icon: RiEyeOffLine, category: "Security & Status" },
  { name: "RiTeamLine", Icon: RiTeamLine, category: "People" },
  { name: "RiRocketLine", Icon: RiRocketLine, category: "Travel & Maps" },
  { name: "RiRocket2Line", Icon: RiRocket2Line, category: "Travel & Maps" },
  { name: "RiBuildingLine", Icon: RiBuildingLine, category: "General" },
  { name: "RiBuilding2Line", Icon: RiBuilding2Line, category: "General" },
  { name: "RiGlobalLine", Icon: RiGlobalLine, category: "Travel & Maps" },
  { name: "RiTimeLine", Icon: RiTimeLine, category: "General" },
  { name: "RiGitCommitLine", Icon: RiGitCommitLine, category: "General" },
  { name: "RiGitBranchLine", Icon: RiGitBranchLine, category: "General" },
  { name: "RiGitPullRequestLine", Icon: RiGitPullRequestLine, category: "General" },
  { name: "RiGitMergeLine", Icon: RiGitMergeLine, category: "Data & Layout" },
  { name: "RiShieldCheckLine", Icon: RiShieldCheckLine, category: "System" },
  { name: "RiShieldLine", Icon: RiShieldLine, category: "Security & Status" },
  { name: "RiFlashlightLine", Icon: RiFlashlightLine, category: "Devices & Tools" },
  { name: "RiHome5Line", Icon: RiHome5Line, category: "General" },
  { name: "RiHome4Line", Icon: RiHome4Line, category: "General" },
  { name: "RiDashboardLine", Icon: RiDashboardLine, category: "Data & Layout" },
  { name: "RiDashboard3Line", Icon: RiDashboard3Line, category: "Data & Layout" },
  { name: "RiNotification3Line", Icon: RiNotification3Line, category: "System" },
  { name: "RiNotificationLine", Icon: RiNotificationLine, category: "System" },
  { name: "RiMailLine", Icon: RiMailLine, category: "Communication & Media" },
  { name: "RiMailOpenLine", Icon: RiMailOpenLine, category: "Communication & Media" },
  { name: "RiMailSendLine", Icon: RiMailSendLine, category: "Communication & Media" },
  { name: "RiCalendarLine", Icon: RiCalendarLine, category: "General" },
  { name: "RiCalendar2Line", Icon: RiCalendar2Line, category: "General" },
  { name: "RiCalendarEventLine", Icon: RiCalendarEventLine, category: "General" },
  { name: "RiFolderLine", Icon: RiFolderLine, category: "Documents" },
  { name: "RiFolder3Line", Icon: RiFolder3Line, category: "Documents" },
  { name: "RiFolderOpenLine", Icon: RiFolderOpenLine, category: "Documents" },
  { name: "RiImageLine", Icon: RiImageLine, category: "General" },
  { name: "RiImage2Line", Icon: RiImage2Line, category: "General" },
  { name: "RiLockLine", Icon: RiLockLine, category: "Security & Status" },
  { name: "RiLock2Line", Icon: RiLock2Line, category: "Security & Status" },
  { name: "RiLockUnlockLine", Icon: RiLockUnlockLine, category: "Security & Status" },
  { name: "RiHeartLine", Icon: RiHeartLine, category: "Health" },
  { name: "RiHeart3Line", Icon: RiHeart3Line, category: "Health" },
  { name: "RiBookmarkLine", Icon: RiBookmarkLine, category: "Documents" },
  { name: "RiDownloadLine", Icon: RiDownloadLine, category: "General" },
  { name: "RiDownload2Line", Icon: RiDownload2Line, category: "General" },
  { name: "RiUploadLine", Icon: RiUploadLine, category: "General" },
  { name: "RiUpload2Line", Icon: RiUpload2Line, category: "General" },
  { name: "RiShareLine", Icon: RiShareLine, category: "General" },
  { name: "RiShareForwardLine", Icon: RiShareForwardLine, category: "General" },
  { name: "RiDeleteBinLine", Icon: RiDeleteBinLine, category: "General" },
  { name: "RiDeleteBin6Line", Icon: RiDeleteBin6Line, category: "General" },
  { name: "RiEditLine", Icon: RiEditLine, category: "General" },
  { name: "RiEdit2Line", Icon: RiEdit2Line, category: "General" },
  { name: "RiPencilLine", Icon: RiPencilLine, category: "Editor & Design" },
  { name: "RiFilterLine", Icon: RiFilterLine, category: "System" },
  { name: "RiFilter3Line", Icon: RiFilter3Line, category: "System" },
  { name: "RiSortDesc", Icon: RiSortDesc, category: "System" },
  { name: "RiSortAsc", Icon: RiSortAsc, category: "System" },
  { name: "RiRefreshLine", Icon: RiRefreshLine, category: "System" },
  { name: "RiLoopLeftLine", Icon: RiLoopLeftLine, category: "System" },
  { name: "RiExternalLinkLine", Icon: RiExternalLinkLine, category: "Editor & Design" },
  { name: "RiLinkM", Icon: RiLinkM, category: "Editor & Design" },
  { name: "RiLink", Icon: RiLink, category: "Editor & Design" },
  { name: "RiLinkUnlinkM", Icon: RiLinkUnlinkM, category: "Editor & Design" },
  { name: "RiCodeLine", Icon: RiCodeLine, category: "Editor & Design" },
  { name: "RiCodeSSlashLine", Icon: RiCodeSSlashLine, category: "Editor & Design" },
  { name: "RiTerminalBoxLine", Icon: RiTerminalBoxLine, category: "Editor & Design" },
  { name: "RiTerminalLine", Icon: RiTerminalLine, category: "Editor & Design" },
  { name: "RiCloudLine", Icon: RiCloudLine, category: "Weather & Nature" },
  { name: "RiCloudOffLine", Icon: RiCloudOffLine, category: "Weather & Nature" },
  { name: "RiDatabase2Line", Icon: RiDatabase2Line, category: "System" },
  { name: "RiServerLine", Icon: RiServerLine, category: "Devices & Tools" },
  { name: "RiCpuLine", Icon: RiCpuLine, category: "Devices & Tools" },
  { name: "RiSmartphoneLine", Icon: RiSmartphoneLine, category: "Communication & Media" },
  { name: "RiComputerLine", Icon: RiComputerLine, category: "Devices & Tools" },
  { name: "RiMacbookLine", Icon: RiMacbookLine, category: "Documents" },
  { name: "RiTabletLine", Icon: RiTabletLine, category: "Data & Layout" },
  { name: "RiMoonLine", Icon: RiMoonLine, category: "Weather & Nature" },
  { name: "RiSunLine", Icon: RiSunLine, category: "Weather & Nature" },
  { name: "RiMapPinLine", Icon: RiMapPinLine, category: "Travel & Maps" },
  { name: "RiMapPin2Line", Icon: RiMapPin2Line, category: "Travel & Maps" },
  { name: "RiPhoneLine", Icon: RiPhoneLine, category: "Communication & Media" },
  { name: "RiChat1Line", Icon: RiChat1Line, category: "System" },
  { name: "RiChat3Line", Icon: RiChat3Line, category: "System" },
  { name: "RiMessage2Line", Icon: RiMessage2Line, category: "Communication & Media" },
  { name: "RiMessage3Line", Icon: RiMessage3Line, category: "Communication & Media" },
  { name: "RiQuestionLine", Icon: RiQuestionLine, category: "Communication & Media" },
  { name: "RiQuestionnaireLine", Icon: RiQuestionnaireLine, category: "Communication & Media" },
  { name: "RiAlarmLine", Icon: RiAlarmLine, category: "General" },
  { name: "RiTimerLine", Icon: RiTimerLine, category: "General" },
  { name: "RiHistoryLine", Icon: RiHistoryLine, category: "General" },
  { name: "RiBarChartLine", Icon: RiBarChartLine, category: "Data & Layout" },
  { name: "RiBarChart2Line", Icon: RiBarChart2Line, category: "Data & Layout" },
  { name: "RiBarChartBoxLine", Icon: RiBarChartBoxLine, category: "Data & Layout" },
  { name: "RiLineChartLine", Icon: RiLineChartLine, category: "Data & Layout" },
  { name: "RiPieChartLine", Icon: RiPieChartLine, category: "Data & Layout" },
  { name: "RiPieChart2Line", Icon: RiPieChart2Line, category: "Data & Layout" },
  { name: "RiWalletLine", Icon: RiWalletLine, category: "Finance & Commerce" },
  { name: "RiWallet3Line", Icon: RiWallet3Line, category: "Finance & Commerce" },
  { name: "RiCoinLine", Icon: RiCoinLine, category: "Finance & Commerce" },
  { name: "RiCoinsLine", Icon: RiCoinsLine, category: "Finance & Commerce" },
  { name: "RiShoppingBagLine", Icon: RiShoppingBagLine, category: "Finance & Commerce" },
  { name: "RiStore2Line", Icon: RiStore2Line, category: "Finance & Commerce" },
  { name: "RiGiftLine", Icon: RiGiftLine, category: "Finance & Commerce" },
  { name: "RiTicketLine", Icon: RiTicketLine, category: "Finance & Commerce" },
  { name: "RiCouponLine", Icon: RiCouponLine, category: "Finance & Commerce" },
  { name: "RiTrophyLine", Icon: RiTrophyLine, category: "Finance & Commerce" },
  { name: "RiMedalLine", Icon: RiMedalLine, category: "Finance & Commerce" },
  { name: "RiAwardLine", Icon: RiAwardLine, category: "Finance & Commerce" },
  { name: "RiVipCrownLine", Icon: RiVipCrownLine, category: "Finance & Commerce" },
  { name: "RiMagicLine", Icon: RiMagicLine, category: "Devices & Tools" },
  { name: "RiSparklingLine", Icon: RiSparklingLine, category: "Devices & Tools" },
  { name: "RiSparkling2Line", Icon: RiSparkling2Line, category: "Devices & Tools" },
  { name: "RiLayoutLine", Icon: RiLayoutLine, category: "Data & Layout" },
  { name: "RiLayout4Line", Icon: RiLayout4Line, category: "Data & Layout" },
  { name: "RiLayoutGridLine", Icon: RiLayoutGridLine, category: "Data & Layout" },
  { name: "RiGridLine", Icon: RiGridLine, category: "Data & Layout" },
  { name: "RiListCheck", Icon: RiListCheck, category: "System" },
  { name: "RiListCheck2", Icon: RiListCheck2, category: "System" },
  { name: "RiMenuLine", Icon: RiMenuLine, category: "System" },
  { name: "RiMenu2Line", Icon: RiMenu2Line, category: "System" },
  { name: "RiSideBarLine", Icon: RiSideBarLine, category: "General" },
  { name: "RiFullscreenLine", Icon: RiFullscreenLine, category: "System" },
  { name: "RiZoomInLine", Icon: RiZoomInLine, category: "System" },
  { name: "RiZoomOutLine", Icon: RiZoomOutLine, category: "System" },
  { name: "RiPrinterLine", Icon: RiPrinterLine, category: "Documents" },
  { name: "RiSave3Line", Icon: RiSave3Line, category: "Documents" },
  { name: "RiClipboardLine", Icon: RiClipboardLine, category: "Documents" },
  { name: "RiFileCopyLine", Icon: RiFileCopyLine, category: "Documents" },
  { name: "RiFileCopy2Line", Icon: RiFileCopy2Line, category: "Documents" },
  { name: "RiAttachmentLine", Icon: RiAttachmentLine, category: "System" },
  { name: "RiAttachment2", Icon: RiAttachment2, category: "System" },
  { name: "RiMicLine", Icon: RiMicLine, category: "Communication & Media" },
  { name: "RiMicOffLine", Icon: RiMicOffLine, category: "Communication & Media" },
  { name: "RiVideoLine", Icon: RiVideoLine, category: "Communication & Media" },
  { name: "RiVideoAddLine", Icon: RiVideoAddLine, category: "System" },
  { name: "RiCameraLine", Icon: RiCameraLine, category: "Communication & Media" },
  { name: "RiMusic2Line", Icon: RiMusic2Line, category: "Communication & Media" },
  { name: "RiPlayLine", Icon: RiPlayLine, category: "Communication & Media" },
  { name: "RiPauseLine", Icon: RiPauseLine, category: "Communication & Media" },
  { name: "RiStopLine", Icon: RiStopLine, category: "Communication & Media" },
  { name: "RiSkipForwardLine", Icon: RiSkipForwardLine, category: "Communication & Media" },
  { name: "RiSkipBackLine", Icon: RiSkipBackLine, category: "Communication & Media" },
  { name: "RiVolumeUpLine", Icon: RiVolumeUpLine, category: "Communication & Media" },
  { name: "RiVolumeMuteLine", Icon: RiVolumeMuteLine, category: "Communication & Media" },
  { name: "RiFlagLine", Icon: RiFlagLine, category: "General" },
  { name: "RiFlag2Line", Icon: RiFlag2Line, category: "General" },
  { name: "RiPushpinLine", Icon: RiPushpinLine, category: "Travel & Maps" },
  { name: "RiPushpin2Line", Icon: RiPushpin2Line, category: "Travel & Maps" },
  { name: "RiKeyLine", Icon: RiKeyLine, category: "Security & Status" },
  { name: "RiKey2Line", Icon: RiKey2Line, category: "Security & Status" },
  { name: "RiFingerprintLine", Icon: RiFingerprintLine, category: "Security & Status" },
  { name: "RiUserAddLine", Icon: RiUserAddLine, category: "System" },
  { name: "RiUserFollowLine", Icon: RiUserFollowLine, category: "People" },
  { name: "RiGroupLine", Icon: RiGroupLine, category: "People" },
  { name: "RiGroup2Line", Icon: RiGroup2Line, category: "People" },
  { name: "RiUserStarLine", Icon: RiUserStarLine, category: "People" },
  { name: "RiUserSettingsLine", Icon: RiUserSettingsLine, category: "People" },
  { name: "RiBriefcaseLine", Icon: RiBriefcaseLine, category: "General" },
  { name: "RiBriefcase4Line", Icon: RiBriefcase4Line, category: "General" },
  { name: "RiSuitcaseLine", Icon: RiSuitcaseLine, category: "General" },
  { name: "RiSunCloudyLine", Icon: RiSunCloudyLine, category: "Weather & Nature" },
  { name: "RiRainyLine", Icon: RiRainyLine, category: "Weather & Nature" },
  { name: "RiFireLine", Icon: RiFireLine, category: "Weather & Nature" },
  { name: "RiDropLine", Icon: RiDropLine, category: "Weather & Nature" },
  { name: "RiCompassLine", Icon: RiCompassLine, category: "Travel & Maps" },
  { name: "RiTranslate2", Icon: RiTranslate2, category: "System" },
  { name: "RiFontSize", Icon: RiFontSize, category: "Editor & Design" },
  { name: "RiText", Icon: RiText, category: "Editor & Design" },
  { name: "RiH1", Icon: RiH1, category: "Editor & Design" },
  { name: "RiH2", Icon: RiH2, category: "Editor & Design" },
  { name: "RiListOrdered", Icon: RiListOrdered, category: "Communication & Media" },
  { name: "RiListUnordered", Icon: RiListUnordered, category: "Communication & Media" },
  { name: "RiDoubleQuotesL", Icon: RiDoubleQuotesL, category: "Editor & Design" },
  { name: "RiTableLine", Icon: RiTableLine, category: "Data & Layout" },
  { name: "RiFunctionLine", Icon: RiFunctionLine, category: "Editor & Design" },
  { name: "RiBracesLine", Icon: RiBracesLine, category: "Editor & Design" },
  { name: "RiGithubLine", Icon: RiGithubLine, category: "Brands" },
  { name: "RiGithubFill", Icon: RiGithubFill, category: "Brands" },
  { name: "RiTwitterXLine", Icon: RiTwitterXLine, category: "Brands" },
  { name: "RiGoogleLine", Icon: RiGoogleLine, category: "Brands" },
  { name: "RiGoogleFill", Icon: RiGoogleFill, category: "Brands" },
  { name: "RiAppleLine", Icon: RiAppleLine, category: "Brands" },
  { name: "RiAppleFill", Icon: RiAppleFill, category: "Brands" },
  { name: "RiFigmaLine", Icon: RiFigmaLine, category: "Brands" },
  { name: "RiSlackLine", Icon: RiSlackLine, category: "Brands" },
  { name: "RiNotionLine", Icon: RiNotionLine, category: "Brands" },
  { name: "RiLinkedinBoxLine", Icon: RiLinkedinBoxLine, category: "Brands" },
  { name: "RiMicrosoftLine", Icon: RiMicrosoftLine, category: "Brands" },
  { name: "RiReactjsLine", Icon: RiReactjsLine, category: "Brands" },
  { name: "RiTailwindCssLine", Icon: RiTailwindCssLine, category: "Brands" },
  { name: "RiNextjsLine", Icon: RiNextjsLine, category: "Brands" },
  { name: "RiBox3Line", Icon: RiBox3Line, category: "Devices & Tools" },
  { name: "RiArchiveLine", Icon: RiArchiveLine, category: "Documents" },
  { name: "RiArchiveDrawerLine", Icon: RiArchiveDrawerLine, category: "Documents" },
  { name: "RiStackLine", Icon: RiStackLine, category: "Data & Layout" },
  { name: "RiApps2Line", Icon: RiApps2Line, category: "Devices & Tools" },
  { name: "RiAppsLine", Icon: RiAppsLine, category: "Devices & Tools" },
  { name: "RiToolsLine", Icon: RiToolsLine, category: "Devices & Tools" },
  { name: "RiBugLine", Icon: RiBugLine, category: "Security & Status" },
  { name: "RiEqualizerLine", Icon: RiEqualizerLine, category: "Devices & Tools" },
  { name: "RiEqualizer3Line", Icon: RiEqualizer3Line, category: "Devices & Tools" },
  { name: "RiToggleLine", Icon: RiToggleLine, category: "Devices & Tools" },
  { name: "RiCheckboxLine", Icon: RiCheckboxLine, category: "System" },
  { name: "RiCheckboxBlankLine", Icon: RiCheckboxBlankLine, category: "System" },
  { name: "RiRadioButtonLine", Icon: RiRadioButtonLine, category: "Devices & Tools" },
  { name: "RiCheckboxMultipleLine", Icon: RiCheckboxMultipleLine, category: "System" },
  { name: "RiArrowGoBackLine", Icon: RiArrowGoBackLine, category: "System" },
  { name: "RiArrowGoForwardLine", Icon: RiArrowGoForwardLine, category: "System" },
  { name: "RiExpandUpDownLine", Icon: RiExpandUpDownLine, category: "System" },
  { name: "RiContractUpDownLine", Icon: RiContractUpDownLine, category: "System" },
  { name: "RiHandCoinLine", Icon: RiHandCoinLine, category: "People" },
  { name: "RiThumbUpLine", Icon: RiThumbUpLine, category: "People" },
  { name: "RiThumbDownLine", Icon: RiThumbDownLine, category: "People" },
  { name: "RiEmotionLine", Icon: RiEmotionLine, category: "People" },
  { name: "RiEmotionHappyLine", Icon: RiEmotionHappyLine, category: "People" },
  { name: "RiEmotionSadLine", Icon: RiEmotionSadLine, category: "People" },
  { name: "RiUserSmileLine", Icon: RiUserSmileLine, category: "People" },
  { name: "RiCustomerService2Line", Icon: RiCustomerService2Line, category: "People" },
  { name: "RiBookOpenLine", Icon: RiBookOpenLine, category: "Documents" },
  { name: "RiBook2Line", Icon: RiBook2Line, category: "Documents" },
  { name: "RiBookletLine", Icon: RiBookletLine, category: "Documents" },
  { name: "RiNewspaperLine", Icon: RiNewspaperLine, category: "Documents" },
  { name: "RiArticleLine", Icon: RiArticleLine, category: "Documents" },
  { name: "RiDraftLine", Icon: RiDraftLine, category: "Documents" },
  { name: "RiStickyNoteLine", Icon: RiStickyNoteLine, category: "Documents" },
  { name: "RiTodoLine", Icon: RiTodoLine, category: "Documents" },
  { name: "RiTaskLine", Icon: RiTaskLine, category: "Documents" },
  { name: "RiCalendarCheckLine", Icon: RiCalendarCheckLine, category: "System" },
  { name: "RiCalendarTodoLine", Icon: RiCalendarTodoLine, category: "Documents" },
  { name: "RiLightbulbLine", Icon: RiLightbulbLine, category: "Devices & Tools" },
  { name: "RiLightbulbFlashLine", Icon: RiLightbulbFlashLine, category: "Devices & Tools" },
  { name: "RiFlashlightFill", Icon: RiFlashlightFill, category: "Devices & Tools" },
  { name: "RiSunFill", Icon: RiSunFill, category: "Weather & Nature" },
  { name: "RiMoonFill", Icon: RiMoonFill, category: "Weather & Nature" },
  { name: "RiCloudFill", Icon: RiCloudFill, category: "Weather & Nature" },
  { name: "RiHome5Fill", Icon: RiHome5Fill, category: "General" },
  { name: "RiUser3Fill", Icon: RiUser3Fill, category: "People" },
  { name: "RiSettings3Fill", Icon: RiSettings3Fill, category: "Devices & Tools" },
  { name: "RiNotification3Fill", Icon: RiNotification3Fill, category: "System" },
  { name: "RiMailFill", Icon: RiMailFill, category: "Communication & Media" },
  { name: "RiHeart3Fill", Icon: RiHeart3Fill, category: "Health" },
  { name: "RiBookmarkFill", Icon: RiBookmarkFill, category: "Documents" },
  { name: "RiErrorWarningLine", Icon: RiErrorWarningLine, category: "Security & Status" },
  { name: "RiInformationLine", Icon: RiInformationLine, category: "System" },
  { name: "RiSpam2Line", Icon: RiSpam2Line, category: "Security & Status" },
  { name: "RiShieldKeyholeLine", Icon: RiShieldKeyholeLine, category: "Security & Status" },
  { name: "RiVerifiedBadgeLine", Icon: RiVerifiedBadgeLine, category: "Security & Status" },
  { name: "RiVerifiedBadgeFill", Icon: RiVerifiedBadgeFill, category: "Security & Status" },
  { name: "RiLoader4Line", Icon: RiLoader4Line, category: "System" },
  { name: "RiReplyLine", Icon: RiReplyLine, category: "Communication & Media" },
  { name: "RiFileLine", Icon: RiFileLine, category: "Documents" },
  { name: "RiFile3Line", Icon: RiFile3Line, category: "Documents" },
  { name: "RiFileAddLine", Icon: RiFileAddLine, category: "System" },
  { name: "RiFileDownloadLine", Icon: RiFileDownloadLine, category: "Documents" },
  { name: "RiFileUploadLine", Icon: RiFileUploadLine, category: "Documents" },
  { name: "RiFilePdfLine", Icon: RiFilePdfLine, category: "Documents" },
  { name: "RiFileExcelLine", Icon: RiFileExcelLine, category: "Documents" },
  { name: "RiFileWordLine", Icon: RiFileWordLine, category: "Documents" },
  { name: "RiFilePptLine", Icon: RiFilePptLine, category: "Documents" },
  { name: "RiFileZipLine", Icon: RiFileZipLine, category: "Documents" },
  { name: "RiFileMusicLine", Icon: RiFileMusicLine, category: "Documents" },
  { name: "RiFileVideoLine", Icon: RiFileVideoLine, category: "Documents" },
  { name: "RiFileImageLine", Icon: RiFileImageLine, category: "Documents" },
  { name: "RiFileCodeLine", Icon: RiFileCodeLine, category: "Documents" },
  { name: "RiFolderAddLine", Icon: RiFolderAddLine, category: "System" },
  { name: "RiFolderUploadLine", Icon: RiFolderUploadLine, category: "Documents" },
  { name: "RiFolderDownloadLine", Icon: RiFolderDownloadLine, category: "Documents" },
  { name: "RiHardDriveLine", Icon: RiHardDriveLine, category: "Documents" },
  { name: "RiHardDrive2Line", Icon: RiHardDrive2Line, category: "Documents" },
  { name: "RiPlayListLine", Icon: RiPlayListLine, category: "Communication & Media" },
  { name: "RiRepeatLine", Icon: RiRepeatLine, category: "System" },
  { name: "RiShuffleLine", Icon: RiShuffleLine, category: "Communication & Media" },
  { name: "RiContrastLine", Icon: RiContrastLine, category: "Editor & Design" },
  { name: "RiShapeLine", Icon: RiShapeLine, category: "Editor & Design" },
  { name: "RiSubtractFill", Icon: RiSubtractFill, category: "System" },
  { name: "RiAddFill", Icon: RiAddFill, category: "System" },
  { name: "RiCloseFill", Icon: RiCloseFill, category: "System" },
  { name: "RiCheckFill", Icon: RiCheckFill, category: "System" },
  { name: "RiCheckDoubleLine", Icon: RiCheckDoubleLine, category: "System" },
  { name: "RiThumbUpFill", Icon: RiThumbUpFill, category: "People" },
  { name: "RiHeartFill", Icon: RiHeartFill, category: "Health" },
  { name: "RiStarSFill", Icon: RiStarSFill, category: "General" },
  { name: "RiStarSLine", Icon: RiStarSLine, category: "General" },
  { name: "RiBookmark3Line", Icon: RiBookmark3Line, category: "Documents" },
  { name: "RiFlag2Fill", Icon: RiFlag2Fill, category: "General" },
  { name: "RiPriceTag3Line", Icon: RiPriceTag3Line, category: "Finance & Commerce" },
  { name: "RiSwapLine", Icon: RiSwapLine, category: "System" },
  { name: "RiArrowLeftRightLine", Icon: RiArrowLeftRightLine, category: "System" },
  { name: "RiArrowUpDownLine", Icon: RiArrowUpDownLine, category: "System" },
  { name: "RiFilterOffLine", Icon: RiFilterOffLine, category: "System" },
  { name: "RiSearchEyeLine", Icon: RiSearchEyeLine, category: "Security & Status" },
  { name: "RiZoomInFill", Icon: RiZoomInFill, category: "System" },
  { name: "RiUserSearchLine", Icon: RiUserSearchLine, category: "People" },
  { name: "RiRocketFill", Icon: RiRocketFill, category: "Travel & Maps" },
  { name: "RiFirstAidKitLine", Icon: RiFirstAidKitLine, category: "Health" },
  { name: "RiHeartAddLine", Icon: RiHeartAddLine, category: "System" },
  { name: "RiDislikeLine", Icon: RiDislikeLine, category: "People" },
  { name: "RiZoomOutFill", Icon: RiZoomOutFill, category: "System" },
  { name: "RiDraftFill", Icon: RiDraftFill, category: "Documents" },
] as const;

export const ICON_CATEGORIES = Array.from(new Set(ICONS.map((i) => i.category)));
