#!/usr/bin/env node
/**
 * Unseen quality check — grades every exported component against
 * COMPONENT-QUALITY-SPEC.md §1–§8 and enforces two things:
 *
 *   ratchet  (default with --check) — no component's score may drop below
 *            audit/quality-baseline.json. This is what `npm test` runs.
 *   tier bar (--strict)             — every component must be at or above the
 *            minimum grade for its tier. This is the promotion gate.
 *
 * It also validates WEBSITE-IA.md's taxonomy mechanically (--ia): every routed
 * component belongs to exactly one category, every category is non-empty, and
 * the legacy routes are declared.
 *
 * Companion artifacts:
 *   QUALITY-SCORECARD.md          generated by --md
 *   audit/quality-baseline.json   written by --write-baseline
 *   audit/ia-taxonomy.json        the IA source of truth (hand-maintained)
 *
 * Usage:
 *   node scripts/quality-check.mjs                       human report
 *   node scripts/quality-check.mjs --json                machine-readable
 *   node scripts/quality-check.mjs --md                  write QUALITY-SCORECARD.md
 *   node scripts/quality-check.mjs --check               ratchet vs baseline (exit 1 on drop)
 *   node scripts/quality-check.mjs --strict              tier bar (exit 1 on debt)
 *   node scripts/quality-check.mjs --ia                  IA taxonomy validation only
 *   node scripts/quality-check.mjs --write-baseline F    record current scores
 *
 * NOTE ON HONESTY (spec §9.4): a check that cannot be evaluated prints as
 * SKIP and is excluded from the denominator. It never silently passes.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";

const ROOT = new URL("../", import.meta.url).pathname;
const UI = join(ROOT, "src/ui");
const P = (p) => join(ROOT, p);
const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);
const arg = (f) => (has(f) ? argv[argv.indexOf(f) + 1] : null);
const MODE = has("--json") ? "json" : has("--md") ? "md" : "table";

/* ---------------------------------------------------------------- config */

/** Curated flagship set (spec §2.1). Union with top-12 block usage. */
const TIER_A_CURATED = [
  "Button", "Input", "Select", "Checkbox", "Switch", "Textarea", "Card", "Badge",
  "Avatar", "Tabs", "Modal", "Dropdown", "Table", "DataTable", "Alert", "Toast",
];

/** Sub-parts inherit their parent's docs page (spec §2.1 tier C otherwise). */
const SUBPART_PARENT = {
  CardHeader: "Card", CardBody: "Card", CardFooter: "Card", ScrollShadow: "Card",
  AvatarGroupCompact: "AvatarGroup", ToastProvider: "Toast", ErrorState: "EmptyState",
  CircularProgress: "Progress", Divider: "Card", Code: "Snippet", User: "Avatar",
};

/** Nav titles that do not equal the export name. */
const PAGE_ALIAS = { Kbd: "Keyboard Key", FancyButton: "Fancy Button", ButtonTile: "Button Tile", CompactButton: "Compact Button", LinkButton: "Link Button", SocialButton: "Social Button", ButtonGroup: "Button Group", ToggleGroup: "Toggle Group", RadioGroup: "Radio Group", DigitInput: "Digit Input", LabelHint: "Label & Hint", SelectionCard: "Checkbox & Radio Card", ColorPicker: "Color Picker", StatusBadge: "Status Badge", InfoLabel: "Info Label & Message", ListItem: "List Item", PaymentCard: "Payment Card", FileFormatIcon: "File Format Icon", WidgetBox: "Widget Box", ContentDivider: "Content Divider", TabMenuHorizontal: "Tab Menu Horizontal", TabMenuVertical: "Tab Menu Vertical", SegmentedControl: "Segmented Control", AlertDialog: "Alert Dialog", HoverCard: "Hover Card", EmptyState: "Empty State", FeaturedIcon: "Featured Icon", DataTable: "Data Table", AvatarGroup: "Avatar Group", SidebarNav: "Introduction" };

const TIER_MIN = { A: { score: 90, letter: "A" }, B: { score: 80, letter: "B" }, C: { score: 65, letter: "C" } };
const LETTER_SCORE = { A: 90, B: 80, C: 65, D: 0 };
/** Machine proxy for the category rules in spec §4.3. */
const CELL_FLOOR = { A: 12, B: 6, C: 1 };

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/* ------------------------------------------------------------ component scan */

const uiFiles = readdirSync(UI).filter((f) => f.endsWith(".tsx")).sort();
const sources = Object.fromEntries(uiFiles.map((f) => [f, readFileSync(join(UI, f), "utf8")]));

const rows = [];
for (const file of uiFiles) {
  const src = sources[file];
  const bounds = [...src.matchAll(/\nexport\s+(?:function|const)\s+([A-Z][A-Za-z0-9]*)/g)].map((m) => ({ name: m[1], at: m.index }));
  const seen = {};
  bounds.forEach((b, i) => {
    const end = bounds[i + 1]?.at ?? src.length;
    const chunk = src.slice(b.at, end);
    /* shared helpers defined above the export still describe the component */
    const window2 = src.slice(Math.max(0, b.at - 4000), Math.min(src.length, end + 2000));
    /* identity: file::name, disambiguated by occurrence — export names are not unique */
    const n = (seen[b.name] = (seen[b.name] ?? 0) + 1);
    const id = `ui/${file}::${b.name}${n > 1 ? `#${n}` : ""}`;
    rows.push({ id, file: `ui/${file}`, name: b.name, chunk, window: window2 });
  });
}

/* ------------------------------------------------------------- docs chain */

const navSrc = readFileSync(P("src/docs/nav.ts"), "utf8");
const navItems = [...navSrc.matchAll(/\{\s*title:\s*"([^"]+)",\s*href:\s*"([^"]+)"/g)].map((m) => ({ title: m[1], href: m[2], key: norm(m[1]) }));
const navByKey = new Map(navItems.map((n) => [n.key, n]));

const registrySrc = readFileSync(P("src/pages/registry.tsx"), "utf8");
const routeToDoc = new Map();
for (const m of registrySrc.matchAll(/"([a-z0-9/-]+)":\s*\([^)]*\)\s*=>\s*<([A-Za-z0-9_]+)/g)) routeToDoc.set(m[1], m[2]);

const docFiles = readdirSync(P("src/pages/components")).filter((f) => f.endsWith(".tsx"));
const docSource = new Map(); // doc export name -> { file, chunk }
const docNameCollisions = [];
for (const f of docFiles) {
  const src = readFileSync(join(P("src/pages/components"), f), "utf8");
  const bounds = [...src.matchAll(/\nexport\s+function\s+([A-Za-z0-9_]+)/g)].map((m) => ({ name: m[1], at: m.index }));
  /* Local (non-exported) helpers in the same file are part of the page's source:
   * <ButtonPlayground/> is the playground, even though it is not the route export. */
  const helpers = new Map();
  for (const m of src.matchAll(/^function\s+([A-Za-z0-9_]+)/gm)) {
    const next = [...src.matchAll(/^function\s+([A-Za-z0-9_]+)/gm)].map((x) => x.index).find((at) => at > m.index);
    helpers.set(m[1], src.slice(m.index, next ?? src.length));
  }
  bounds.forEach((b, i) => {
    let chunk = src.slice(b.at, bounds[i + 1]?.at ?? src.length);
    for (const [helperName, helperSrc] of helpers) {
      if (chunk.includes(`<${helperName}`)) chunk += "\n" + helperSrc;
    }
    const entry = { file: `src/pages/components/${f}`, chunk };
    if (docSource.has(b.name)) {
      /* Two doc exports may not share a name: grading would read the wrong page. */
      docNameCollisions.push(`${b.name} (${docSource.get(b.name).file} vs ${entry.file})`);
      return;
    }
    docSource.set(b.name, entry);
  });
}
if (docNameCollisions.length) console.error(`✗ duplicate doc export names: ${docNameCollisions.join("; ")}`);

const testSrc = readdirSync(P("tests")).filter((f) => /\.test\.tsx?$/.test(f))
  .map((f) => readFileSync(join(P("tests"), f), "utf8")).join("\n");

const blocksSrc = ["src/blocks"].flatMap((d) => readdirSync(P(d)).filter((f) => f.endsWith(".tsx")).map((f) => readFileSync(join(P(d), f), "utf8")))
  .concat([readFileSync(P("src/pages/Templates.tsx"), "utf8")]);
const usageCount = (name) => blocksSrc.reduce((n, s) => n + (s.match(new RegExp(`\\b${name}\\b`, "g"))?.length ?? 0), 0);

/** The docs route a component is published on (sub-parts inherit their parent). */
function routeFor(name) {
  const own = navByKey.get(norm(PAGE_ALIAS[name] ?? name));
  if (own) return own.href;
  const parent = SUBPART_PARENT[name];
  if (parent) {
    const p = navByKey.get(norm(PAGE_ALIAS[parent] ?? parent));
    if (p) return p.href;
  }
  return null;
}

/* tiers: curated ∪ top-12 by block/template usage (spec §2.1) */
const topUsed = [...rows].filter((r) => routeFor(r.name)).sort((a, b) => usageCount(b.name) - usageCount(a.name)).slice(0, 12).map((r) => r.name);
const tierA = new Set([...TIER_A_CURATED, ...topUsed]);
const TIER_A_LIST = [...tierA].join(", ");

/* variant cells — the counting law lives in ONE place: scripts/variant-audit.mjs,
 * which also implements the alias law (spec §3.3). Never re-derive it here. */
const variantAudit = JSON.parse(execSync("node scripts/variant-audit.mjs --json", { cwd: ROOT, encoding: "utf8", maxBuffer: 1 << 24 }));
const variantBy = new Map(variantAudit.rows.map((r) => [r.name, r]));

/* ------------------------------------------------------------- categories */

const FORM_RE = /Input|Textarea|Select|Checkbox|Radio|Switch|Slider|Digit|Datepicker|Calendar|Combobox|Rating|ColorPicker|Uploader|Prompt|Currency|TimePicker|Otp|Label/i;
const ACTION_RE = /Button|Tile|Toolbar|ToggleGroup|ButtonGroup|Link/i;
const LIST_RE = /Table|List|Feed|Timeline|Grid|DataTable|Empty/i;
/** Categories whose required axes are set by CONVENTIONS.md §1.2 (R4/R8). */
const INDICATOR_RE = /Badge|Chip|Tag|Avatar|Card|StatusBadge|Progress|Table|DataTable|WidgetBox|Well|Skeleton/i;
const OVERLAY_RE = /Modal|Dialog|Drawer|Popover|Tooltip|Dropdown|Menu|HoverCard|Toast|Command/i;

function categoryOf({ name, file }) {
  if (ACTION_RE.test(name)) return "action";
  if (FORM_RE.test(name) || /Form\.tsx/.test(file)) return "form";
  if (OVERLAY_RE.test(name) || /Overlay\.tsx/.test(file)) return "overlay";
  if (LIST_RE.test(name)) return "list";
  return "display";
}

/* ----------------------------------------------------------------- checks */

function gradeComponent(row) {
  const { name, file, chunk, window: w } = row;
  const cat = categoryOf(row);
  const va = variantBy.get(name);
  const axes = va?.axes ?? {};
  const cells = va?.cells ?? 0;
  const aliasProps = Object.keys(va?.aliases ?? {});
  const interactive = cat === "action" || cat === "form" || cat === "overlay" || cat === "list";
  const a11yRelevant = interactive || /aria-|role=/.test(w);

  /* docs chain */
  const route = routeFor(name);
  const docEntry = route ? docSource.get(routeToDoc.get(route) ?? "") : null;
  const docChunk = docEntry?.chunk ?? "";
  const hasRoute = Boolean(route);
  /* JSX is frequently formatted across lines — flatten before scanning the page */
  const flatDoc = docChunk.replace(/\s+/g, " ");

  const checks = [];
  const add = (matrix, id, ok, note, applicable = true) => checks.push({ matrix, id, applicable, ok: applicable ? ok : null, note });

  /* --- M1 contract --- */
  add("M1", "ref", /forwardRef|ref\?:/.test(w), "forwardRef / ref prop");
  add("M1", "cn", /\bcn\(/.test(chunk), "cn() merge");
  const axesRequired = interactive || INDICATOR_RE.test(name);
  add("M1", "axes", Object.keys(axes).length > 0, "typed axis unions", axesRequired);
  add("M1", "polymorphic", /asChild|href\?:/.test(chunk), "asChild / href", cat === "action");
  add("M1", "controlled", /defaultValue|defaultChecked/.test(chunk), "controlled + uncontrolled parity", /onChange|onValueChange|onCheckedChange/.test(chunk));
  const aliasTypes = [...chunk.matchAll(/^(?:export\s+)?type\s+([A-Z][A-Za-z0-9]*Alias)\s*=/gm)].map((m) => m[1]);
  add("M1", "alias-counted", aliasProps.length === 0 || cells > 0, `alias props not double-counted (${aliasProps.join(", ") || "none"})`, aliasProps.length > 0);
  add("M1", "alias-law", aliasTypes.length === 0 || /Alias|alias/i.test(docChunk), `alias layer documented (${aliasTypes.join(", ") || "none"})`, aliasTypes.length > 0);

  /* --- M2 variant matrix --- */
  add("M2", "axes", Object.keys(axes).length >= 1, `axes: ${Object.keys(axes).join("+") || "none"}`, axesRequired);
  add("M2", "cells", cells >= CELL_FLOOR[row.tier], `${cells} cells (floor ${CELL_FLOOR[row.tier]})`, Object.keys(axes).length > 0);
  add("M2", "matrix-rendered", /title="(Variants|Matrix)[^"]*"/.test(flatDoc) && /\.map\(/.test(flatDoc), "matrix rendered from axis arrays", hasRoute && Object.keys(axes).length > 0);

  /* --- M3 states --- */
  add("M3", "disabled", /\bdisabled\b|isDisabled/.test(w), "disabled state", interactive);
  add("M3", "loading", /\b(loading|isLoading|busy)\b/.test(w), "loading state", cat === "action" || cat === "form");
  add("M3", "error", /error|invalid|aria-invalid/.test(w), "error/invalid state", cat === "form");
  add("M3", "focus", /focus-visible|focus:shadow-ring|focus:ring/.test(w), "focus-visible ring", interactive);
  add("M3", "empty", /empty/i.test(chunk), "empty state", cat === "list");
  add("M3", "unit-test", new RegExp(`\\b${name}\\b`).test(testSrc), "unit/interaction test mentions it", interactive);

  /* --- M4 visual --- */
  const lintIssues = [];
  if (/#[0-9a-fA-F]{6}\b/.test(chunk) && !/Extra\.tsx|Patterns\.tsx|More\.tsx/.test(file)) lintIssues.push("raw hex");
  if (/\b(bg|text|ring|border)-(slate|zinc|stone|indigo|violet|emerald|rose|amber|lime|cyan)-\d{2,3}\b/.test(chunk)) lintIssues.push("raw palette");
  if (/\b(text-xs|text-sm|text-base|text-lg|text-xl|text-2xl|text-3xl)\b/.test(chunk)) lintIssues.push("off-scale type");
  if (/\bfont-semibold\b/.test(chunk)) lintIssues.push("weight");
  if (/\bshadow-e[1-5]\b/.test(chunk)) lintIssues.push("legacy elevation");
  add("M4", "design-lint", lintIssues.length === 0, lintIssues.length ? `lint: ${lintIssues.join(", ")}` : "token-clean");
  const tokenHits = (chunk.match(/\b(surface|surface-secondary|foreground|muted|subtle|border|border-strong|field|accent|success|warning|danger|ring)-/g) ?? []).length;
  const tokenFloor = row.tier === "C" ? 1 : 3;
  add("M4", "tokens", tokenHits >= tokenFloor, `${tokenHits} semantic token classes (floor ${tokenFloor})`);
  const darkLiteral = /(bg|text)-(white|black)\b/.test(chunk.replace(/dark:[^\s"']+/g, ""));
  add("M4", "theme-parity", /dark:/.test(w) || (!darkLiteral && tokenHits >= tokenFloor), "dark parity (dark: or token-driven)");
  add("M4", "geometry", !/\b(h|w|size|gap|p[xytrbl]?|m[xytrbl]?|top|left|right|bottom)-\[/.test(chunk), "geometry from scale (no arbitrary brackets)");
  const animates = /animate-|transition/.test(chunk);
  add("M4", "motion", !animates || /motion-(reduce|safe)|animate-(spin-slow|fade-in|pop-in|slide-up)|duration-\(--/.test(chunk), "motion token / reduced-motion", animates);

  /* --- M5 accessibility --- */
  add("M5", "aria", /aria-/.test(w), "aria-* contract", a11yRelevant);
  add("M5", "role", /role\s*=/.test(chunk) || /<(button|input|label|select|table|nav|a|ul|ol|li)\b/.test(chunk), "explicit role or native semantics", interactive);
  add("M5", "keyboard", /onKeyDown|e\.key|key ===/.test(w), "keyboard handlers", /role=/.test(chunk) && cat !== "form");
  add("M5", "ids", /useId/.test(w), "useId for generated ids", /aria-describedby|aria-labelledby|htmlFor/.test(w));
  add("M5", "route-covered", hasRoute, "route covered by axe gates", row.tier !== "C");
  /* an icon-only usage needs a name in the examples users copy, not in the component */
  add("M5", "icon-label", /aria-label/.test(docChunk || w), "icon-only accessible name in examples", /iconOnly|isIconOnly/.test(w));

  /* --- M6 documentation --- */
  const docApplies = row.tier !== "C";
  const sections = [...flatDoc.matchAll(/Section title="([^"]*)"/g)].map((m) => m[1]);
  const canonical = ["Variants", "Matrix", "Sizes", "States", "Accessibility", "API", "Source"];
  const anatomy = canonical.filter((c) => sections.some((s) => new RegExp(c, "i").test(s))).length;
  const anatomyFloor = row.tier === "A" ? 5 : 4;
  if (process.env.QUALITY_DEBUG && name === "Button") console.log("DEBUG", JSON.stringify({ route, hasRoute, doc: Boolean(docEntry), flatLen: flatDoc.length, sections, anatomy, anatomyFloor }));
  add("M6", "page", hasRoute, route ? `/${route}` : "no docs route", docApplies);
  add("M6", "anatomy", anatomy >= anatomyFloor, `${anatomy}/${canonical.length} sections (floor ${anatomyFloor})`, docApplies && hasRoute);
  add("M6", "playground", /controls=|<Playground/.test(flatDoc), "inline playground with controls", row.tier === "A" && hasRoute);
  add("M6", "api", /<PropsTable/.test(flatDoc), "API props table", docApplies && hasRoute);
  add("M6", "code", /<Showcase[^>]*code=|code=/.test(flatDoc) || /<CodeBlock/.test(flatDoc), "copyable code samples", docApplies && hasRoute);
  add("M6", "a11y-section", sections.some((s) => /Accessibility/i.test(s)), "Accessibility section on the page", row.tier === "A" && hasRoute);

  const applicable = checks.filter((c) => c.applicable);
  const passed = applicable.filter((c) => c.ok);
  const score = applicable.length ? Math.round((passed.length / applicable.length) * 1000) / 10 : 0;
  let grade = score >= 90 ? "A" : score >= 80 ? "B" : score >= 65 ? "C" : "D";
  const a11yFail = checks.some((c) => c.applicable && c.ok === false && (c.matrix === "M5" || (c.matrix === "M4" && c.id === "theme-parity")));
  if (a11yFail && (grade === "A" || grade === "B")) grade = "C"; // spec §1.1 ground rule
  return { ...row, cat, axes, cells, checks, applicable: applicable.length, passed: passed.length, skipped: checks.length - applicable.length, score, grade, route, hasRoute, cells_floor: CELL_FLOOR[row.tier] };
}

for (const r of rows) r.tier = tierA.has(r.name) ? "A" : routeFor(r.name) ? "B" : "C";
const graded = rows.map((r) => Object.assign(r, gradeComponent(r)));

/* ------------------------------------------------------- IA taxonomy check */

function iaReport() {
  const tax = JSON.parse(readFileSync(P("audit/ia-taxonomy.json"), "utf8"));
  const members = Object.entries(tax.members);
  const problems = [];
  const componentNav = navItems.filter((n) => n.href.startsWith("components/"));
  for (const n of componentNav) if (!tax.members[n.href]) problems.push(`unmapped nav route: ${n.href}`);
  for (const [href, cat] of members) {
    if (!componentNav.some((n) => n.href === href)) problems.push(`taxonomy references a route not in nav: ${href}`);
    if (!tax.categories.some((c) => c.key === cat)) problems.push(`unknown category "${cat}" for ${href}`);
  }
  for (const c of tax.categories) if (!members.some(([, k]) => k === c.key)) problems.push(`empty category: ${c.key}`);
  for (const l of tax.legacyRoutes ?? []) {
    if (!registrySrc.includes(`"${l.route}"`)) problems.push(`legacy route declared but not registered: ${l.route}`);
    if (!registrySrc.includes(`"${l.canonical}"`)) problems.push(`legacy route target missing: ${l.canonical}`);
  }
  const counts = Object.fromEntries(tax.categories.map((c) => [c.key, members.filter(([, k]) => k === c.key).length]));
  return { tax, members, problems, counts, pro: tax.proBadge.length, legacy: tax.legacyRoutes.length };
}

/* ----------------------------------------------------------------- output */

const ia = iaReport();
const byGrade = { A: 0, B: 0, C: 0, D: 0 };
const byTier = { A: 0, B: 0, C: 0 };
for (const r of graded) { byGrade[r.grade]++; byTier[r.tier]++; }
const mean = Math.round(graded.reduce((p, r) => p + r.score, 0) / graded.length * 10) / 10;
const atBar = graded.filter((r) => LETTER_SCORE[r.grade] >= TIER_MIN[r.tier].score).length;
const debt = graded.filter((r) => LETTER_SCORE[r.grade] < TIER_MIN[r.tier].score).sort((a, b) => a.score - b.score);
const totalCells = variantAudit.total;
const withAxes = variantAudit.withAxes;

const failing = (r) => r.checks.filter((c) => c.applicable && !c.ok).map((c) => `${c.matrix}.${c.id}`);

if (MODE === "json") {
  console.log(JSON.stringify({
    total: graded.length, withAxes, totalCells, mean, atBar,
    byGrade, byTier, ia: { counts: ia.counts, problems: ia.problems },
    components: graded.map((r) => ({ id: r.id, name: r.name, file: r.file, tier: r.tier, score: r.score, grade: r.grade, cells: r.cells, route: r.route, failing: failing(r) })),
  }, null, 2));
} else if (MODE === "table" && !has("--ia") && !has("--check") && !has("--write-baseline")) {
  console.log(`\nUnseen quality report — ${graded.length} components · ${withAxes} axis-bearing · ${totalCells} cells`);
  console.log(`mean score ${mean} · at/above tier bar ${atBar}/${graded.length} · grades A:${byGrade.A} B:${byGrade.B} C:${byGrade.C} D:${byGrade.D}\n`);
  const nameW = Math.max(...graded.map((r) => r.name.length), 4);
  console.log(`${"Component".padEnd(nameW)}  Tier  Score  Grade  Cells  Failing`);
  for (const r of [...graded].sort((a, b) => (TIER_MIN[a.tier].score - a.score) - (TIER_MIN[b.tier].score - b.score))) {
    const f = failing(r);
    console.log(`${r.name.padEnd(nameW)}  ${r.tier}     ${String(r.score).padStart(5)}  ${r.grade}      ${String(r.cells).padStart(4)}   ${f.slice(0, 4).join(", ")}${f.length > 4 ? ` +${f.length - 4}` : ""}`);
  }
  console.log(`\nIA taxonomy: ${ia.members.length}/${ia.members.length} mapped · categories ${Object.entries(ia.counts).map(([k, v]) => `${k} ${v}`).join(" · ")}`);
  if (ia.problems.length) { console.log("IA problems:"); for (const p of ia.problems) console.log("  ✗ " + p); }
  else console.log("IA problems: none");
  console.log(`\nDebt (below tier bar): ${debt.length}` + (debt.length ? ` → ${debt.slice(0, 10).map((d) => `${d.name}(${d.score})`).join(", ")}${debt.length > 10 ? " …" : ""}` : ""));
}

if (has("--ia")) {
  console.log(`\nWEBSITE-IA taxonomy — ${ia.members.length} components in ${ia.tax.categories.length} categories`);
  for (const c of ia.tax.categories) {
    const rows2 = Object.entries(ia.tax.members).filter(([, k]) => k === c.key).map(([h]) => ia.tax.titles[h]);
    console.log(`\n${c.title} (${rows2.length}) — ${c.blurb}\n  ${rows2.join(", ")}`);
  }
  console.log(`\nPro badges: ${ia.pro} · legacy routes declared: ${ia.legacy}`);
  if (ia.problems.length) { for (const p of ia.problems) console.log("  ✗ " + p); process.exit(1); }
  console.log("IA problems: none");
}

if (MODE === "md") {
  const lines = [];
  lines.push("# Unseen Quality Scorecard (generated)", "",
    "> Regenerate with: `npm run quality:report -- --md`",
    "> Standard: `COMPONENT-QUALITY-SPEC.md` — this file is that spec applied to the current source.",
    "> Ratchet: `audit/quality-baseline.json` · Gate: `npm test` (`quality:check`) · Promotion: `quality:check -- --strict`", "",
    `**Tier A (flagship):** ${TIER_A_LIST}`, "",
    `**${graded.length} components** · **${withAxes}** axis-bearing · **${totalCells}** variant cells · mean score **${mean}** · at or above tier bar **${atBar}/${graded.length}**`,
    `Grades: A ${byGrade.A} · B ${byGrade.B} · C ${byGrade.C} · D ${byGrade.D} — Tiers: A ${byTier.A} · B ${byTier.B} · C ${byTier.C}`, "",
    "## Grades by component", "",
    "| Component | File | Tier | Cells | Score | Grade | At bar | Failing checks |",
    "|---|---|---|---|---|---|---|---|");
  for (const r of [...graded].sort((a, b) => (a.tier + a.name).localeCompare(b.tier + b.name) || b.score - a.score)) {
    const f = failing(r);
    lines.push(`| ${r.name} | \`${r.file}\` | ${r.tier} | ${r.cells} | ${r.score} | ${r.grade} | ${LETTER_SCORE[r.grade] >= TIER_MIN[r.tier].score ? "✓" : "✗"} | ${f.join(", ") || "—"} |`);
  }
  lines.push("", "## Debt ledger (below tier bar, worst first)", "",
    "| Component | Tier | Score | Grade | Needs |", "|---|---|---|---|---|");
  for (const r of debt) lines.push(`| ${r.name} | ${r.tier} | ${r.score} | ${r.grade} | ${failing(r).join(", ") || "—"} |`);
  lines.push("", "## IA taxonomy (WEBSITE-IA.md §3)", "",
    `Mapped: **${ia.members.length}** components · Categories: ${Object.entries(ia.counts).map(([k, v]) => `${k} ${v}`).join(" · ")} · Pro badges: ${ia.pro} · Legacy routes: ${ia.legacy}`, "",
    ia.problems.length ? ia.problems.map((p) => `- ✗ ${p}`).join("\n") : "No orphans, no unmapped routes, no empty categories.", "");
  writeFileSync(P("QUALITY-SCORECARD.md"), lines.join("\n"));
  console.log(`Wrote QUALITY-SCORECARD.md — ${graded.length} components, mean ${mean}, debt ${debt.length}.`);
}

/* ------------------------------------------------------------ baselines */

if (has("--write-baseline")) {
  const file = arg("--write-baseline");
  const payload = {
    at: new Date().toISOString().slice(0, 10),
    total: graded.length,
    mean,
    components: Object.fromEntries(graded.map((r) => [r.id, { score: r.score, grade: r.grade, tier: r.tier, cells: r.cells, name: r.name, file: r.file }])),
  };
  writeFileSync(P(file), JSON.stringify(payload, null, 2) + "\n");
  console.log(`Wrote ${file} — ${graded.length} components, mean ${mean}.`);
}

if (has("--check")) {
  const file = arg("--check") && !arg("--check").startsWith("--") ? arg("--check") : "audit/quality-baseline.json";
  if (!existsSync(P(file))) { console.error(`✗ ratchet baseline missing: ${file}`); process.exit(1); }
  const base = JSON.parse(readFileSync(P(file), "utf8"));
  const regressions = [];
  for (const r of graded) {
    const b = base.components[r.id];
    if (!b) { regressions.push(`${r.name} (${r.file}): new since baseline (score ${r.score}) — refreeze the baseline in this PR`); continue; }
    if (r.score < b.score) regressions.push(`${r.name} (${r.file}): ${b.score} → ${r.score} (regression)`);
  }
  for (const k of Object.keys(base.components)) if (!graded.some((r) => r.id === k)) regressions.push(`${base.components[k].name ?? k}: disappeared since baseline`);
  /* alias law: cells must not fall below the variant-audit baseline either */
  const vb = P("audit/variant-audit-baseline.json");
  if (existsSync(vb)) {
    const vbase = JSON.parse(readFileSync(vb, "utf8"));
    if (variantAudit.total < vbase.total) regressions.push(`variant cells: ${vbase.total} → ${variantAudit.total} (cell regression)`);
  }
  if (ia.problems.length) for (const p of ia.problems) regressions.push(`IA: ${p}`);
  if (regressions.length) {
    console.error(`\n✗ quality ratchet failed (${regressions.length}):`);
    for (const r of regressions) console.error("  " + r);
    process.exit(1);
  }
  console.log(`✓ quality ratchet holds — ${graded.length} components ≥ baseline (mean ${mean}).`);
}

if (has("--strict")) {
  const below = graded.filter((r) => r.score < TIER_MIN[r.tier].score);
  if (below.length) {
    console.error(`\n✗ tier bar not met (${below.length} components):`);
    for (const r of below) console.error(`  ${r.tier} ${r.name}: ${r.score} (needs ${TIER_MIN[r.tier].score}) — ${failing(r).join(", ")}`);
    process.exit(1);
  }
  console.log(`✓ every component meets its tier bar (${graded.length} components).`);
}
